# GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
# DO NOT EDIT — edit the schema and regenerate.
#
# THIS LAYER'S REALIZATION. Six arrays, split twice — who WRITES a lane
# decides where it lives; who READS it decides whether it lives at all:
#   static (sm f32 + fl u32)      decode's output; a pure function of the byte
#   positional (lm f32 + lc u32)  the fold's output; render-read
#   witness (wm f32 + wc u32)     fold interior no render path reads; the
#                                 serial form writes it only when witnessed
# Float carriers hold measures, u32 carriers hold counts — no bitcasts, and
# a count cannot land in a float array by accident.
#
# Strides and lane indices below are THIS BACKEND'S and are not prescribed
# to anyone. What is shared lives in glyphContract.js: the record format and
# the kind of each field. Another layer may realize the same kinds in a
# different container and stay conformant; what it owes is the assertion
# that its own mapping respects them, which validate() performs for this one.

# ── The SLOT BUFFERS: six arrays, split twice ─────────────────────────────
# static  = decode's output (pure function of the byte); positional = the
# fold's render-read output; witness = fold interior no render path reads.
# Decode NEVER touches positional or witness — that is the write-axis split.
# LM/LC = layout measures/counts; SM = static measures; WM/WC = witness;
# FLAGS is its own stride-1 array (flags[id], no lane constant needed).
comptime SM_STRIDE = 4
comptime SM_ADVANCE = 0
comptime SM_HEIGHT = 1
comptime SM_GLYPH_ID = 2
comptime SM_PAD = 3
comptime FLAGS_STRIDE = 1

comptime LM_STRIDE = 4
comptime LM_X = 0
comptime LM_Y = 1
comptime LM_Z = 2
comptime LM_BASE_X = 3

comptime LC_STRIDE = 2
comptime LC_ROW = 0
comptime LC_COL = 1

# Witness arrays (read-axis split): stride-1, indexed by byte. The scan form
# allocates them; the serial form only under its witness instantiation.
comptime WM_STRIDE = 1
comptime WC_STRIDE = 1

# The RECORD format (the wire): unchanged by either split. A record is emitted
# as three runs — posMeasures[0..3), staticMeasures[0..3), posCounts WHOLE —
# a concatenation of truncations, still no lane map.
comptime RECORD_MEASURE_STRIDE = 6
comptime RECORD_COUNT_STRIDE = 2
comptime RECORD_BYTES = 32

# ── THE FIXTURE FORMAT — frozen on disk (format v2), independent of the
#    container. Fixtures carry the oracle's VALUES in this order; the engine's
#    buffers may be re-laid at will and the fixtures do not move.
comptime FIXTURE_MEASURE_STRIDE = 8
comptime FIX_M_X = 0
comptime FIX_M_Y = 1
comptime FIX_M_Z = 2
comptime FIX_M_ADVANCE = 3
comptime FIX_M_HEIGHT = 4
comptime FIX_M_GLYPH_ID = 5
comptime FIX_M_BASE_X = 6
comptime FIX_M_LINE_ADV = 7

comptime FIXTURE_COUNT_STRIDE = 4
comptime FIX_C_ROW = 0
comptime FIX_C_COL = 1
comptime FIX_C_FLAGS = 2
comptime FIX_C_ORD = 3

# The scan partial (ScanElem) in a GPU buffer — same kind rule.
comptime PARTIAL_COUNT_STRIDE = 7
comptime P_RESET = 0
comptime P_NL = 1
comptime P_GLYPHS = 2
comptime P_ROWS = 3
comptime P_HEAD_LEN = 4
comptime P_TAIL_LEN = 5
comptime P_WRAP = 6

comptime PARTIAL_MEASURE_STRIDE = 1
comptime PM_TAIL_ADV = 0

# Per-item layout params on device — f32, because Metal has no f64.
comptime ITEM_STRIDE = 15
comptime I_ORIGIN_Y = 0
comptime I_ORIGIN_Z = 1
comptime I_PAGE_ROWS = 2
comptime I_PAGE_COLS = 3
comptime I_SCROLL_ROWS = 4
comptime I_PAGES_WIDE = 5
comptime I_WRAP_WIDTH = 6
comptime I_LINE_HEIGHT = 7
comptime I_Z_STEP = 8
comptime I_BAND_STRIDE_Y = 9
comptime I_DEPTH_PER_BAND = 10
comptime I_DEPTH_PER_COL = 11
comptime I_PAGE_STRIDE_X = 12
comptime I_HAS_PAGE = 13
comptime I_ORIGIN_X = 14

# Per-item bounds + fold scalars. Lane kinds matter on device: Metal has no f64,
# so counts go to native u32 atomics and measures to f32 ordered keys.
comptime BOUNDS_STRIDE = 8
comptime B_MIN_X = 0
comptime B_MIN_Y = 1
comptime B_MIN_Z = 2
comptime B_MAX_X = 3
comptime B_MAX_Y = 4
comptime B_MAX_Z = 5
comptime B_TOTAL_ROWS = 6
comptime B_MAX_ROW_EXTENT = 7
comptime BOUNDS_COUNT_LANES = (6)


def fixture_measure_lane_name(lane: Int) -> String:
    '''FIXTURE lane name for diagnostics (fixture order, not container order).'''
    if lane == 0:
        return "X"
    if lane == 1:
        return "Y"
    if lane == 2:
        return "Z"
    if lane == 3:
        return "ADVANCE"
    if lane == 4:
        return "HEIGHT"
    if lane == 5:
        return "GLYPH_ID"
    if lane == 6:
        return "BASE_X"
    if lane == 7:
        return "LINE_ADV"
    return "M_?"


def fixture_count_lane_name(lane: Int) -> String:
    if lane == 0:
        return "ROW"
    if lane == 1:
        return "COL"
    if lane == 2:
        return "FLAGS"
    if lane == 3:
        return "ORD"
    return "C_?"
