// GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
// DO NOT EDIT — edit the schema and regenerate.
//
// THIS LAYER'S REALIZATION. Six arrays, split twice — who WRITES a lane
// decides where it lives; who READS it decides whether it lives at all:
//   static (sm f32 + fl u32)      decode's output; a pure function of the byte
//   positional (lm f32 + lc u32)  the fold's output; render-read
//   witness (wm f32 + wc u32)     fold interior no render path reads; the
//                                 serial form writes it only when witnessed
// Float carriers hold measures, u32 carriers hold counts — no bitcasts, and
// a count cannot land in a float array by accident.
//
// Strides and lane indices below are THIS BACKEND'S and are not prescribed
// to anyone. What is shared lives in glyphContract.js: the record format and
// the kind of each field. Another layer may realize the same kinds in a
// different container and stay conformant; what it owes is the assertion
// that its own mapping respects them, which validate() performs for this one.

// ── THE FIXTURE FORMAT (frozen, v2) — what gen.mjs writes to disk ─────────
export const FIXTURE_MEASURE_STRIDE = 8;
export const FIX_M_X = 0;
export const FIX_M_Y = 1;
export const FIX_M_Z = 2;
export const FIX_M_ADVANCE = 3;
export const FIX_M_HEIGHT = 4;
export const FIX_M_GLYPH_ID = 5;
export const FIX_M_BASE_X = 6;
export const FIX_M_LINE_ADV = 7;

export const FIXTURE_COUNT_STRIDE = 4;
export const FIX_C_ROW = 0;
export const FIX_C_COL = 1;
export const FIX_C_FLAGS = 2;
export const FIX_C_ORD = 3;

// ── This backend's WORKING container (the phase split) ────────────────────
export const SM_STRIDE = 2;
export const SM_ADVANCE = 0;
export const SM_HEIGHT = 1;

export const LM_STRIDE = 4;
export const LM_X = 0;
export const LM_Y = 1;
export const LM_Z = 2;
export const LM_BASE_X = 3;

export const LC_STRIDE = 2;
export const LC_ROW = 0;
export const LC_COL = 1;

export const GI_STRIDE = 1;

export const RECORD_MEASURE_STRIDE = 5;
export const RECORD_COUNT_STRIDE = 3;

export const IM_STRIDE = 9;
export const IM_ORIGIN_Y = 0;
export const IM_ORIGIN_Z = 1;
export const IM_LINE_HEIGHT = 2;
export const IM_Z_STEP = 3;
export const IM_BAND_STRIDE_Y = 4;
export const IM_DEPTH_PER_BAND = 5;
export const IM_DEPTH_PER_COL = 6;
export const IM_PAGE_STRIDE_X = 7;
export const IM_ORIGIN_X = 8;

export const IE_STRIDE = 6;
export const IE_PAGE_ROWS = 0;
export const IE_PAGE_COLS = 1;
export const IE_SCROLL_ROWS = 2;
export const IE_PAGES_WIDE = 3;
export const IE_WRAP_WIDTH = 4;
export const IE_HAS_PAGE = 5;

export const BOUNDS_STRIDE = 8;
export const B_MIN_X = 0;
export const B_MIN_Y = 1;
export const B_MIN_Z = 2;
export const B_MAX_X = 3;
export const B_MAX_Y = 4;
export const B_MAX_Z = 5;
export const B_TOTAL_ROWS = 6;
export const B_MAX_ROW_EXTENT = 7;
