# GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
# DO NOT EDIT — edit the schema and regenerate.
#
# THIS LAYER'S REALIZATION. Two buffers, and where a value lives IS what
# kind it is:
#   measures (f32) — where things are in space; rounding is load-bearing.
#   counts   (u32) — what the data is; exact to 2^32, never rounded.
# There are no bitcasts. A count cannot land in the float buffer by accident.
#
# Strides and lane indices below are THIS BACKEND'S and are not prescribed
# to anyone. What is shared lives in glyphContract.js: the record format and
# the kind of each field. Another layer may realize the same kinds in a
# different container and stay conformant; what it owes is the assertion
# that its own mapping respects them, which validate() performs for this one.

comptime MEASURE_STRIDE = 8
comptime M_X = 0
comptime M_Y = 1
comptime M_Z = 2
comptime M_ADVANCE = 3
comptime M_HEIGHT = 4
comptime M_GLYPH_ID = 5
comptime M_BASE_X = 6
comptime M_LINE_ADV = 7

comptime COUNT_STRIDE = 4
comptime C_ROW = 0
comptime C_COL = 1
comptime C_FLAGS = 2
comptime C_ORD = 3

# The RECORD format: the render-read prefix of each buffer. Emitting a record
# is a truncation, not a repack — which is why the scratch pool can be reused
# and the resident cost stops scaling with the corpus.
comptime RECORD_MEASURE_STRIDE = 6
comptime RECORD_COUNT_STRIDE = 2
comptime RECORD_BYTES = 32

# The scan partial (ScanElem) in a GPU buffer — same two-buffer rule.
comptime PARTIAL_COUNT_STRIDE = 7
comptime P_RESET = 0
comptime P_NL = 1
comptime P_GLYPHS = 2
comptime P_ROWS = 3
comptime P_HEAD_LEN = 4
comptime P_TAIL_LEN = 5
comptime P_WRAP = 6

comptime PARTIAL_MEASURE_STRIDE = 1
comptime PM_TAIL_ADV = 0

# Per-item layout params on device — f32, because Metal has no f64.
comptime ITEM_STRIDE = 15
comptime I_ORIGIN_Y = 0
comptime I_ORIGIN_Z = 1
comptime I_PAGE_ROWS = 2
comptime I_PAGE_COLS = 3
comptime I_SCROLL_ROWS = 4
comptime I_PAGES_WIDE = 5
comptime I_WRAP_WIDTH = 6
comptime I_LINE_HEIGHT = 7
comptime I_Z_STEP = 8
comptime I_BAND_STRIDE_Y = 9
comptime I_DEPTH_PER_BAND = 10
comptime I_DEPTH_PER_COL = 11
comptime I_PAGE_STRIDE_X = 12
comptime I_HAS_PAGE = 13
comptime I_ORIGIN_X = 14

# Per-item bounds + fold scalars. Lane kinds matter on device: Metal has no f64,
# so counts go to native u32 atomics and measures to f32 ordered keys.
comptime BOUNDS_STRIDE = 8
comptime B_MIN_X = 0
comptime B_MIN_Y = 1
comptime B_MIN_Z = 2
comptime B_MAX_X = 3
comptime B_MAX_Y = 4
comptime B_MAX_Z = 5
comptime B_TOTAL_ROWS = 6
comptime B_MAX_ROW_EXTENT = 7
comptime BOUNDS_COUNT_LANES = (6)


def measure_lane_name(lane: Int) -> String:
    """Lane name for diagnostics — runtime lookup (comptime lists cannot materialize)."""
    if lane == 0:
        return "M_X"
    if lane == 1:
        return "M_Y"
    if lane == 2:
        return "M_Z"
    if lane == 3:
        return "M_ADVANCE"
    if lane == 4:
        return "M_HEIGHT"
    if lane == 5:
        return "M_GLYPH_ID"
    if lane == 6:
        return "M_BASE_X"
    if lane == 7:
        return "M_LINE_ADV"
    return "M_?"


def count_lane_name(lane: Int) -> String:
    if lane == 0:
        return "C_ROW"
    if lane == 1:
        return "C_COL"
    if lane == 2:
        return "C_FLAGS"
    if lane == 3:
        return "C_ORD"
    return "C_?"
