// GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
// DO NOT EDIT — edit the schema and regenerate.
//
// THIS LAYER'S REALIZATION. Two buffers, and where a value lives IS what
// kind it is:
//   measures (f32) — where things are in space; rounding is load-bearing.
//   counts   (u32) — what the data is; exact to 2^32, never rounded.
// There are no bitcasts. A count cannot land in the float buffer by accident.
//
// Strides and lane indices below are THIS BACKEND'S and are not prescribed
// to anyone. What is shared lives in glyphContract.js: the record format and
// the kind of each field. Another layer may realize the same kinds in a
// different container and stay conformant; what it owes is the assertion
// that its own mapping respects them, which validate() performs for this one.

export const MEASURE_STRIDE = 8;
export const M_X = 0;
export const M_Y = 1;
export const M_Z = 2;
export const M_ADVANCE = 3;
export const M_HEIGHT = 4;
export const M_GLYPH_ID = 5;
export const M_BASE_X = 6;
export const M_LINE_ADV = 7;

export const COUNT_STRIDE = 4;
export const C_ROW = 0;
export const C_COL = 1;
export const C_FLAGS = 2;
export const C_ORD = 3;

export const RECORD_MEASURE_STRIDE = 6;
export const RECORD_COUNT_STRIDE = 2;

export const ITEM_STRIDE = 16;
export const I_ORIGIN_Y = 0;
export const I_ORIGIN_Z = 1;
export const I_PAGE_ROWS = 2;
export const I_PAGE_COLS = 3;
export const I_SCROLL_ROWS = 4;
export const I_PAGES_WIDE = 5;
export const I_WRAP_WIDTH = 6;
export const I_LINE_HEIGHT = 7;
export const I_PAGE_LINE_HEIGHT = 8;
export const I_Z_STEP = 9;
export const I_BAND_STRIDE_Y = 10;
export const I_DEPTH_PER_BAND = 11;
export const I_DEPTH_PER_COL = 12;
export const I_PAGE_STRIDE_X = 13;
export const I_HAS_PAGE = 14;
export const I_ORIGIN_X = 15;

export const BOUNDS_STRIDE = 8;
export const B_MIN_X = 0;
export const B_MIN_Y = 1;
export const B_MIN_Z = 2;
export const B_MAX_X = 3;
export const B_MAX_Y = 4;
export const B_MAX_Z = 5;
export const B_TOTAL_ROWS = 6;
export const B_MAX_ROW_EXTENT = 7;
