// GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
// DO NOT EDIT — edit the schema and regenerate.
//
// Two buffers, and where a value lives IS what kind it is:
//   measures (f32) — where things are in space; rounding is load-bearing.
//   counts   (u32) — what the data is; exact to 2^32, never rounded.
// There are no bitcasts. A count cannot land in the float buffer by accident.

export const MEASURE_STRIDE = 8;
export const M_X = 0;
export const M_Y = 1;
export const M_Z = 2;
export const M_ADVANCE = 3;
export const M_HEIGHT = 4;
export const M_GLYPH_ID = 5;
export const M_BASE_X = 6;
export const M_LINE_ADV = 7;

export const COUNT_STRIDE = 4;
export const C_ROW = 0;
export const C_COL = 1;
export const C_FLAGS = 2;
export const C_ORD = 3;

/** The RECORD format: the render-read prefix of each buffer (a truncation). */
export const RECORD_MEASURE_STRIDE = 6;
export const RECORD_COUNT_STRIDE = 2;
export const RECORD_BYTES = 32;

export const PARTIAL_COUNT_STRIDE = 7;
export const P_RESET = 0;
export const P_NL = 1;
export const P_GLYPHS = 2;
export const P_ROWS = 3;
export const P_HEAD_LEN = 4;
export const P_TAIL_LEN = 5;
export const P_WRAP = 6;

export const PARTIAL_MEASURE_STRIDE = 1;
export const PM_TAIL_ADV = 0;

/** Lanes the vertex path reads, in each buffer. */
export const MEASURE_VERTEX_LANES = Object.freeze([M_X, M_Y, M_Z, M_ADVANCE, M_HEIGHT, M_GLYPH_ID]);
export const COUNT_VERTEX_LANES = Object.freeze([C_ROW, C_COL]);
/** Fold scratch — needed while computing, never read by the render path. */
export const MEASURE_SCRATCH_LANES = Object.freeze([M_BASE_X, M_LINE_ADV]);
export const COUNT_SCRATCH_LANES = Object.freeze([C_ORD]);
