// GENERATED by tools/gen-schema.mjs from schema/glyph-identity.json.
// DO NOT EDIT — edit the schema and regenerate.
//
// THE SHARED TIER, and nothing else. Names and kinds — no strides, no lane
// indices, nothing about how any layer stores anything. The renderer runs one
// buffer; the native backend runs four phase arrays; the live item table is
// stride 15 against the backend's 15. All are conformant: container is a
// per-layer realization and KIND is the declared fact.
//
// What every layer owes: assert that its own mapping respects KIND below, and
// produce RECORD_* exactly. Nothing more.

// ── PINNED BIT-FOR-BIT: the record is the wire ─────────────────────────────
/** Per-glyph record: the bytes that cross from a layout backend to a renderer.
 *  Order is part of the format. Emitting one is a TRUNCATION of whatever the
 *  producer keeps internally, never a repack — validate() enforces that every
 *  render-read field sorts before every unread one. */
/** Every record field is one 4-byte carrier (f32 or u32); validate() refuses
 *  a schema where that stops being true, so RECORD_BYTES is DERIVED here and
 *  cannot silently disagree with the field lists below. */
export const RECORD_FIELD_BYTES = 4;
export const RECORD_BYTES = 8 * RECORD_FIELD_BYTES;
export const RECORD_MEASURES = Object.freeze(['X', 'Y', 'Z', 'ADVANCE', 'HEIGHT', 'GLYPH_ID']);
export const RECORD_COUNTS = Object.freeze(['ROW', 'COL']);

// ── KNOWN DEVIATIONS: declared, justified, and still violations ────────────
/** Fields whose kind is EXACT but which ride a float carrier TODAY, with the
 *  reason. A layer asserting KIND needs this to tell a real violation from the
 *  documented one — without it the contract states a rule that NO layer
 *  currently satisfies, and the first assertion written against it fails for a
 *  reason its author cannot act on. Deviations are debts, not exemptions. */
export const KNOWN_DEVIATIONS = Object.freeze({
    GLYPH_ID: "This is an IDENTITY living in the staticMeasures f32 array. It is here only because it is copied verbatim from the trie's f32 blocks, so it cannot move until the TRIE FORMAT moves. It is the single exception in the system and it is deliberately visible: one identity, in the wrong array, naming its own fix.",
});

// ── SHARED SEMANTICS: kinds, not containers ────────────────────────────────
/** KIND per field. Every layer must ASSERT its own mapping respects these —
 *  that assertion is what a layer owes; its lane numbering is its own affair. */
export const KIND = Object.freeze({
    X: 'measure',
    Y: 'measure',
    Z: 'measure',
    BASE_X: 'measure',
    LINE_ADV: 'measure',
    ROW: 'count',
    COL: 'count',
    ORD: 'count',
    ADVANCE: 'measure',
    HEIGHT: 'measure',
    GLYPH_ID: 'identity',
    FLAGS: 'bitfield',
    ORIGIN_Y: 'measure',
    ORIGIN_Z: 'measure',
    PAGE_ROWS: 'measure',
    PAGE_COLS: 'measure',
    SCROLL_ROWS: 'measure',
    PAGES_WIDE: 'measure',
    WRAP_WIDTH: 'measure',
    LINE_HEIGHT: 'measure',
    Z_STEP: 'measure',
    BAND_STRIDE_Y: 'measure',
    DEPTH_PER_BAND: 'measure',
    DEPTH_PER_COL: 'measure',
    PAGE_STRIDE_X: 'measure',
    HAS_PAGE: 'count',
    ORIGIN_X: 'measure',
    MIN_X: 'measure',
    MIN_Y: 'measure',
    MIN_Z: 'measure',
    MAX_X: 'measure',
    MAX_Y: 'measure',
    MAX_Z: 'measure',
    TOTAL_ROWS: 'count',
    MAX_ROW_EXTENT: 'measure',
});

/** EXACT fields: counts, identities and bitfields. Must never ride a float
 *  carrier — and a float ordered key IS a float carrier wearing a u32 costume. */
export const EXACT_FIELDS = Object.freeze(['ROW', 'COL', 'ORD', 'GLYPH_ID', 'FLAGS', 'HAS_PAGE', 'TOTAL_ROWS']);
export const MEASURE_FIELDS = Object.freeze(['X', 'Y', 'Z', 'BASE_X', 'LINE_ADV', 'ADVANCE', 'HEIGHT', 'ORIGIN_Y', 'ORIGIN_Z', 'PAGE_ROWS', 'PAGE_COLS', 'SCROLL_ROWS', 'PAGES_WIDE', 'WRAP_WIDTH', 'LINE_HEIGHT', 'Z_STEP', 'BAND_STRIDE_Y', 'DEPTH_PER_BAND', 'DEPTH_PER_COL', 'PAGE_STRIDE_X', 'ORIGIN_X', 'MIN_X', 'MIN_Y', 'MIN_Z', 'MAX_X', 'MAX_Y', 'MAX_Z', 'MAX_ROW_EXTENT']);
/** MEASURE_FIELDS and EXACT_FIELDS are DISJOINT and EXHAUSTIVE over KIND —
 *  asserted by the generator, so a consumer that classifies lanes in two
 *  buckets can rely on totality. KIND keeps the finer distinction (identity vs
 *  count vs bitfield) for anyone who needs it; nobody has to handle a third
 *  bucket to stay correct. */

/** Fields the vertex path reads. */
export const VERTEX_READ = Object.freeze(['X', 'Y', 'Z', 'ADVANCE', 'HEIGHT', 'GLYPH_ID', 'ROW', 'COL']);

/** The SET of per-item layout parameters both layers must be able to express.
 *  Names and kinds only — where they sit in anyone's item table is not shared. */
export const ITEM_PARAMS = Object.freeze(['ORIGIN_X', 'ORIGIN_Y', 'ORIGIN_Z', 'WRAP_WIDTH', 'Z_STEP', 'LINE_HEIGHT', 'SCROLL_ROWS', 'PAGE_ROWS', 'PAGE_COLS', 'PAGES_WIDE', 'BAND_STRIDE_Y', 'DEPTH_PER_BAND', 'DEPTH_PER_COL', 'PAGE_GAP_X']);

/** Per-item bounds fields, and which of them are exact (never an ordered key). */
export const BOUNDS_FIELDS = Object.freeze(['MIN_X', 'MIN_Y', 'MIN_Z', 'MAX_X', 'MAX_Y', 'MAX_Z', 'TOTAL_ROWS', 'MAX_ROW_EXTENT']);
export const BOUNDS_EXACT_FIELDS = Object.freeze(['TOTAL_ROWS']);
